"""initial chat schema

Revision ID: 233b5fdd6252
Revises:
Create Date: 2026-07-25 20:18:18.851343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233b5fdd6252'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_type', 'name', name='uq_org_unit_type_name')
    )
    with op.batch_alter_table('org_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_units_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_units_unit_type'), ['unit_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['occupation_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_employment_status'), ['employment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created_action', ['created_at', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)

    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('scope_unit_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_unit_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'scope_unit_id', name='uq_room_kind_scope')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index('ix_rooms_active_kind', ['is_active', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_scope_unit_id'), ['scope_unit_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('resident_ref', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_resident_ref'), ['resident_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_room_id'), ['room_id'], unique=False)
        batch_op.create_index('ix_messages_room_id_id', ['room_id', 'id'], unique=False)
        batch_op.create_index('ix_messages_sender_created', ['sender_id', 'created_at'], unique=False)

    op.create_table('room_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_membership')
    )
    with op.batch_alter_table('room_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_memberships_user_active', ['user_id', 'left_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_memberships_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_memberships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_memberships_room_id'))
        batch_op.drop_index('ix_memberships_user_active')

    op.drop_table('room_memberships')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_sender_created')
        batch_op.drop_index('ix_messages_room_id_id')
        batch_op.drop_index(batch_op.f('ix_messages_room_id'))
        batch_op.drop_index(batch_op.f('ix_messages_resident_ref'))
        batch_op.drop_index(batch_op.f('ix_messages_message_type'))

    op.drop_table('messages')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_scope_unit_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_kind'))
        batch_op.drop_index(batch_op.f('ix_rooms_is_active'))
        batch_op.drop_index('ix_rooms_active_kind')

    op.drop_table('rooms')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_expires_at'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.drop_index('ix_audit_created_action')

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_employment_status'))

    op.drop_table('users')
    with op.batch_alter_table('org_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_units_unit_type'))
        batch_op.drop_index(batch_op.f('ix_org_units_is_active'))

    op.drop_table('org_units')
    # ### end Alembic commands ###
