"""add auth security controls

Revision ID: f00e52892218
Revises: 233b5fdd6252
Create Date: 2026-07-25 23:35:42.077285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f00e52892218"
down_revision: Union[str, Sequence[str], None] = "233b5fdd6252"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("client_key", sa.String(length=64), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_login_attempt_client_time",
        "login_attempts",
        ["client_key", "attempted_at"],
        unique=False,
    )
    op.create_index(
        "ix_login_attempt_pair_time",
        "login_attempts",
        ["username", "client_key", "attempted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_login_attempts_attempted_at"),
        "login_attempts",
        ["attempted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_login_attempts_client_key"),
        "login_attempts",
        ["client_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_login_attempts_username"),
        "login_attempts",
        ["username"],
        unique=False,
    )

    op.add_column(
        "login_sessions",
        sa.Column("client_key", sa.String(length=64), nullable=True),
    )
    op.create_index(
        op.f("ix_login_sessions_client_key"),
        "login_sessions",
        ["client_key"],
        unique=False,
    )

    op.add_column(
        "users",
        sa.Column(
            "must_change_password",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "users",
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_users_must_change_password"),
        "users",
        ["must_change_password"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_must_change_password"), table_name="users")
    op.drop_column("users", "password_changed_at")
    op.drop_column("users", "must_change_password")

    op.drop_index(
        op.f("ix_login_sessions_client_key"),
        table_name="login_sessions",
    )
    op.drop_column("login_sessions", "client_key")

    op.drop_index(op.f("ix_login_attempts_username"), table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_client_key"), table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_attempted_at"), table_name="login_attempts")
    op.drop_index("ix_login_attempt_pair_time", table_name="login_attempts")
    op.drop_index("ix_login_attempt_client_time", table_name="login_attempts")

    op.drop_table("login_attempts")
    # ### end Alembic commands ###
